"""Добавлено место аренды

Revision ID: 2925aaa277a7
Revises: 8707ac4ad60e
Create Date: 2025-03-04 15:19:22.669275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2925aaa277a7'
down_revision = '8707ac4ad60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=200), nullable=False))
        batch_op.create_index(batch_op.f('ix_product_type'), ['type'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_type'))
        batch_op.drop_column('type')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
