"""Убираем уникальность type

Revision ID: f82af233e420
Revises: 2925aaa277a7
Create Date: 2025-03-04 16:02:23.444710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82af233e420'
down_revision = '2925aaa277a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('ix_product_type')
        batch_op.create_index(batch_op.f('ix_product_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_type'))
        batch_op.create_index('ix_product_type', ['type'], unique=1)

    # ### end Alembic commands ###
